services:
  postgres:
    image: postgres:16
    container_name: postgres-controldeacceso
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: controldeacceso
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - access-net

  backend:
    build: ./backend
    container_name: backend-service
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - face-service
    environment:
      DATABASE_URL: "postgresql://dev:dev@postgres:5432/controldeacceso"
      FACE_SERVICE_URL: http://face-service:5000
    networks:
      - access-net
    # --- AQUÍ ESTÁ EL VOLUMEN MÁGICO ---
    volumes:
      # Conecta tu carpeta de Windows con la del contenedor
      - ./backend/public:/usr/src/app/public

  face-service:
    build: ./face-service
    container_name: face-service
    restart: always
    ports:
      - "5000:5000"
    networks:
      - access-net

volumes:
  postgres_data:

networks:
  access-net:
    driver: bridge
